# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87c8217d234bd546880a30d19c7f3f3c2e5fd672989487fdc89d9f8cb29ee965eafbad0ecca8a071ee487c5999818b3a91027bad43e1bf9892780bf193f412d7

test:
  secret_key_base: e9dfa2c0e31c43b5f118586d6bd571cd534f8d3f0ce5645af008ef8ecd5da23894d918972584172f701e46c80f5143c5eb8f550a70bef375575905cb3bd3131b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
